### PR TITLE
Fix delayed Pipeline closure

### LINKED ISSUE #194: `TcpClient` leaks connection
I don't know if this is an expected behavior, but it seems that a TcpClient somehow leaks its internal connection (a TcpStream instance?) into the tokio_core::reactor::Core it's running on.

I created an [example test case][1] that has two tests. One test forces the Core instance to drop before the test asserts that the connection is closed (somewhat indirectly, by checking if a dummy server thread has finished). The other lets the Core instance live beyond the assertion, so it's only dropped in the end of the test. The first test succeeds, while the second fails.

[1]: https://github.com/jvff/possible_tokio-proto_tcpclient_connection_leak

### PR DESCRIPTION
**Pull request by cramertj**
Fix #194

### CODE REVIEW

**Comment by cramertj** [comment]
Huh, seems like the timeout I set was too low, so it's racing. I'll raise it when I get to a computer.

**Comment by cramertj** [comment]
Apparently also fixes #181.

**Comment by cramertj** [comment]
Ping @alexcrichton

**Comment by alexcrichton** [comment]
This probably wants to be reviewed by @carllerche, I'm not too familiar with it myself

**Comment by cramertj** [comment]
Ping @carllerche

**Pull request merged**
