### PR TITLE
Use Poll in Parse interface.

### PR DESCRIPTION
**Pull request by tmiasko**
This PR changes the Parse interface to:

``` rust
fn parse(&mut self, buf: &mut BlockBuf) -> Poll<Self::Out, io::Error>;
fn done(&mut self, buf: &mut BlockBuf) -> Poll<Self::Out, io::Error>;
```

Where `Poll<I, E>` is `Result<Async<I>, E>`.

Fatal parsing errors are made explicit by the use of result type #51. Valid
framings that describe an error response are expected to be included as a
variant of `Self::Out` as before.

The readiness is signalled using `Async` for consistency with futures and
streams in general

The default implementation for done is provided that returns error when there
are leftover data after parsing has finished #52.

The `NotReady` is included as a possible return value of done method, to avoid
forcing all implementers to include EOF markers in their data types if such
marker would otherwise be unnecessary.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r+ from me, thoughts @carllerche?

**Comment by carllerche** [comment]
Ha, I didn't see this :(

Switching to poll seems fine, but I also think that we should take some time to rethink the Framed type in general as well as if pinning it to BlockBuf is correct.

**Comment by carllerche** [comment]
cc @aturon

**Comment by aturon** [comment]
I'd like to avoid this for simplicity's sake; the framing helpers are increasingly intended to provide the easiest route to working with I/O objects, so I want to be careful to avoid adding too many knobs/too much functionality. For example, in [my recent PR](https://github.com/tokio-rs/tokio-core/pull/95) encoding/decoding are simplified by removing their persistent state. We're anticipating providing richer forms of framing over time, possibly within the wider Tokio ecosystem.

**Comment by carllerche** [comment]
Thanks for the PR. I'm going to close this as the direction of the encoding / decoding has changed a bit. There will, however, be more in this space as Tokio 0.2 starts happening.

**Pull request closed without merging**
