### PR TITLE
check body readiness

### PR DESCRIPTION
**Pull request by fafhrd91**
If transport flushed and we still reading body we have to check
body readiness, if body is ready then nothing is scheduled and pipeline would stale forever.

### CODE REVIEW

**Comment by carllerche** [comment]
They, thanks for the PR. I'm not exactly following the failure case. Would you be able to supply a test that fails without this change?

**Comment by fafhrd91** [comment]
sure, will provide one tomorrow.

**Comment by fafhrd91** [comment]
@carllerche it is actually quite tricky to reproduce with test case and i am not very experienced in rust/tokio 
could you check #48 first and then depends on that i'll implement real app that shows the problem

**Comment by carllerche** [comment]
Ok, master handles this case. However, it has revealed a trickier issue...

Either way, tokio-proto is moving to use `Stream + Sink`, so hopefully this will resolve the original issue. If not, lets discuss more on Gitter.

**Pull request closed without merging**
