### PR TITLE
tokio_proto::pipeline::Frame is a leaking abstraction

### PR DESCRIPTION
**Pull request by fafhrd91**
Frame reveals unnecessary information, especially for Serializer. I think there should be two specific frame type.

### CODE REVIEW

**Comment by carllerche** [comment]
Could you explain some more of your reasoning.

I'm not sure why `LastChunk` should be on `Frame`. I know that something similar is needed as part of `Framed` parsing, but I believe it can be encapsulated there.

I'm on the fence about `Message` taking `Option` body  vs. `MessageWithBody`. Requiring passing `Option` is pretty annoying to deal with when there is no streaming body like tokio-line.

**Comment by fafhrd91** [comment]
I agree on encapsulation, i changed PR.
if body is encapsulated then maybe `Message` should be encapsulated too. But i don't really have strong opinion on that.

**Comment by carllerche** [comment]
I'm not really understanding why `LastChunk` needs to be part of `Frame`. Also, how should protocols who can't detect the last body chunk behave? For example, HTTP 1.1 w/ transfer-encoding chunked is unable to know the last chunk.

**Comment by fafhrd91** [comment]
actually chunked encoding is easy, if you get `\0\r\n\r\n` then it is last. but chunked it is slightly different because there is special data marker that indicates end of body.

i have problem with `content-length` requests, here is my code::
https://github.com/fafhrd91/simplehttp/blob/master/src/request.rs#L178-L185
basically when i get to the state with `remaining == 0` client already sent all data and we won't get any readiness events from loop.

**Comment by fafhrd91** [comment]
i maybe be doing something wrong :)

**Comment by carllerche** [comment]
I'm going to close this for now. I think that `Frame` has and will evolve more. Hopefully the original issues have been resolved? If not, maybe we can discuss more in Gitter to figure out a path forward.

**Pull request closed without merging**
