### PR TITLE
Use BodyChunk enum instead of option for Frame::Body

### PR DESCRIPTION
**Pull request by fafhrd91**
There should be way how parser can indicate that it returns last chunk.

Here is example, let's say http client sends request with some `CONTENT-LENGTH` = XX
when parser receives last chunk of data, it returns it from `parse`, but problem is that client never sends any more data, so parser never get called again and can not indicate that frame is completed.

### CODE REVIEW

**Comment by fafhrd91** [comment]
forgot to mention. `transport.rd` is empty, so `Framed::read` never calls `parser` again.

**Comment by carllerche** [comment]
This is a good point. I'm going to temporarily hold off merging this as I want to take a moment to think about this issue + a few other issues together.

**Comment by carllerche** [comment]
Thinking a bit more about this, I'm thinking that this is more of an issue with `Framed`. My guess is the return value from `parse` should take something more along these lines...

**Comment by fafhrd91** [comment]
i have another problem implementing http, i'll have better pr later that should solve both problems.

**Pull request closed without merging**
