### PR TITLE
Pull up dependencies

### PR DESCRIPTION
**Pull request by imp**
Update smallvec to a current release

### CODE REVIEW

**Comment by carllerche** [comment]
Looks like CI doesn't pass and there is a merge conflict.

**Comment by imp** [comment]
Rebased

**Comment by imp** [comment]
Mac build fails on 
```
$ pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
/Users/travis/.travis/job_stages: line 57: pip: command not found
```
I am not sure it is related to this PR in any way.

**Comment by imp** [comment]
Also `cargo test` passes on my Mac

**Comment by imp** [comment]
@carllerche ping

**Comment by imp** [comment]
@carllerche There are a few opened pull requests for updating dependencies. Looks like people actively vote for updating. Is there anything that can be done to act on these pull requests?

**Pull request closed without merging**
